name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template and include as many details as possible to help us reproduce and fix the issue.
  - type: textarea
    id: commit
    attributes:
      label: Git commit
      description: Which commit are you trying to compile?
      placeholder: |
        $git rev-parse HEAD
        40a6a8710ec15b1b5db6b5a098409f6bc8f654a4
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System & Version
      placeholder: e.g. “Ubuntu 22.04”, “Windows 11 23H2”, “macOS 14.3”
    validations:
      required: true
  - type: dropdown
    id: backends
    attributes:
        label: GGML backends
        description: Which GGML backends do you know to be affected?
        options: [CPU, CUDA, HIP, Metal, Musa, SYCL, Vulkan, OpenCL]
        multiple: true
    validations:
      required: true
  - type: input
    id: cmd_arguments
    attributes:
      label: Command-line arguments used
      placeholder: The full command line you ran (with all flags)
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      placeholder: A step-by-step list of what you did
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: What you expected to happen
      placeholder: Describe the expected behavior or result
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: What actually happened
      placeholder: Describe what you saw instead (errors, logs, crash, etc.)
    validations:
      required: true
  - type: textarea
    id: logs_and_errors
    attributes:
      label: Logs / error messages / stack trace
      placeholder: Paste complete logs or error output
  - type: textarea
    id: additional_info
    attributes:
      label: Additional context / environment details
      placeholder: e.g. CPU model, GPU, RAM, model file versions, quantization type, etc.
